language: node_js
node_js:
- '12'
branchs:
  only:
  - master
install:
- npm install
script:
- npm run build
env:
  global:
    secure: *********
    addons:
  ssh_known_hosts:
  - 23.105.194.254 #受信主机，你的Linux服务器ip
before_install:
- openssl aes-256-cbc -K $encrypted_1d5e8861dc78_key -iv $encrypted_1d5e8861dc78_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa   #还是Linux文件权限问题
- ssh hjwzzz@23.105.194.254 -o StrictHostKeyChecking=no 'cd ~/blog-front && git pull && npm install && npm run build'   #使用ssh连接服务器
